import type { VisionAnalysis } from "./vision/types.js";

export function generateTestCode(analysis: VisionAnalysis, platform: string, url: string): string {
  const lines: string[] = [];

  if (platform === "webview") {
    lines.push(`// Generated by BugRepro v0.1 — ${new Date().toISOString()}`);
    lines.push(`// Source URL: ${url}`);
    lines.push(`// Page: ${analysis.pageTitle}`);
    lines.push("");
    lines.push(`describe("${analysis.pageTitle}", () => {`);
    lines.push(`  beforeAll(async () => {`);
    lines.push(`    await driver.url("${url}");`);
    lines.push(`  });`);
    lines.push("");

    for (const el of analysis.elements) {
      const testName = `${el.action ?? "verify"} ${el.label}`;
      lines.push(`  it("${testName}", async () => {`);
      if (el.selector) {
        if (el.action === "tap") {
          lines.push(`    await $(${JSON.stringify(el.selector)}).click();`);
        } else if (el.action === "fill") {
          lines.push(`    await $(${JSON.stringify(el.selector)}).setValue("test value");`);
        } else {
          lines.push(`    expect(await $(${JSON.stringify(el.selector)}).isDisplayed()).toBe(true);`);
        }
      }
      lines.push(`  });`);
      lines.push("");
    }

    lines.push(`});`);
  } else {
    // android / ios — Appium Java-style stub
    lines.push(`// Generated by BugRepro v0.1 — ${new Date().toISOString()}`);
    lines.push(`// Source URL: ${url} | Platform: ${platform}`);
    lines.push(`// Page: ${analysis.pageTitle}`);
    lines.push("");
    lines.push(`public class ${toClassName(analysis.pageTitle)}Test {`);
    lines.push("");

    for (const el of analysis.elements) {
      const methodName = toMethodName(`${el.action ?? "verify"}_${el.label}`);
      lines.push(`  @Test`);
      lines.push(`  public void ${methodName}() {`);
      if (el.selector) {
        lines.push(`    MobileElement el = driver.findElement(By.xpath(${JSON.stringify(el.selector)}));`);
        if (el.action === "tap") lines.push(`    el.click();`);
        else if (el.action === "fill") lines.push(`    el.sendKeys("test value");`);
        else lines.push(`    assertTrue(el.isDisplayed());`);
      }
      lines.push(`  }`);
      lines.push("");
    }

    lines.push(`}`);
  }

  return lines.join("\n");
}

function toClassName(s: string): string {
  return s.replace(/[^a-zA-Z0-9 ]/g, "").replace(/\s+(.)/g, (_, c) => c.toUpperCase()).replace(/^\w/, c => c.toUpperCase()) || "Generated";
}

function toMethodName(s: string): string {
  return s.replace(/[^a-zA-Z0-9 _]/g, "").replace(/[\s_]+(.)/g, (_, c) => c.toUpperCase()).replace(/^\w/, c => c.toLowerCase()) || "test";
}
